app/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse

from . import views

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^$', views.landing, name='landing'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^userprofile/$', views.UserProfile.as_view(), name='userprofile'),
]

wmap2018_django/urls.py
from django.conf.urls import url, include
from django.contrib.gis import admin
from rest_framework.authtoken import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', views.obtain_auth_token),
    url('', include('app.urls', namespace="app")),
    url(r'^rest/', include('app.rest_urls', namespace="rest")),
]

app/models.py
# from django.db import models
from django.utils import timezone
from django.contrib.gis.geos import Point

from django.contrib.gis.db import models
from django.contrib.gis import geos
from django.contrib.auth.models import AbstractUser

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class User(AbstractUser):
    last_location = models.PointField(
        verbose_name="last known location",
        blank=True,
        null=True
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    modified = models.DateTimeField(
        auto_now=True
    )

    # objects = models.GeoManager()

    def __str__(self):
        return "{}, ({}), last seen at {} ... cr={}, mod={}" \
            .format(self.username, self.get_full_name(), self.last_location, self.created, self.modified)


class FriendGroup(models.Model):
    class Meta:
        verbose_name = "friends list"
        verbose_name_plural = "friends lists"

    name = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="name"
    )
    owner = models.ForeignKey(
        User,
        related_name="list_owner",
        verbose_name="owner",
        on_delete=models.CASCADE
    )
    members = models.ManyToManyField(
        User,
        through='UserFriendGroup'
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    modified = models.DateTimeField(
        auto_now=True
    )

    # objects = models.Manager()

    def __str__(self):
        return "{} owned by {}".format(self.name, self.owner)


class UserFriendGroup(models.Model):
    class Meta:
        unique_together = ['member', 'friend_group']
        verbose_name = "friend group members"
        verbose_name_plural = "friend group members"

    member = models.ForeignKey(
        User,
        verbose_name="member",
        on_delete=models.CASCADE
    )
    friend_group = models.ForeignKey(
        FriendGroup,
        verbose_name="friend group",
        on_delete=models.CASCADE
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    modified = models.DateTimeField(
        auto_now=True
    )

    # objects = models.Manager()

    def __str__(self):
        return "{} is a member of {}".format(self.member, self.friend_group)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

app/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.forms.forms import NON_FIELD_ERRORS
from django.forms import ModelForm
from . import models

class LoginForm(forms.Form):
    username = forms.CharField(
        label="username",
        max_length=128
    )
    password = forms.CharField(
        label="password",
        max_length=128,
        widget=forms.PasswordInput()
    )


class PasswordForm(forms.Form):
    password = forms.CharField(max_length=128, widget=forms.PasswordInput(), label="Enter password")
    password2 = forms.CharField(max_length=128, widget=forms.PasswordInput(), label="Enter password (again)")

    def clean_password2(self):
        password = self.cleaned_data.get('password', '')
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError("Confirmation password doesn't match.")
        return password2


class SignupForm(PasswordForm):
    username = forms.CharField(
        label="username",
        max_length=30,
        required=True
    )
    first_name = forms.CharField(
        label="first name",
        max_length=30,
        required=True
    )
    last_name = forms.CharField(
        label="last name",
        max_length=30,
        required=True
    )
    email = forms.EmailField(
        label="email",
        max_length=255,
        required=True
    )


class UserProfileForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'last_location']
        widgets = {
            'last_location': forms.HiddenInput()
        }

app/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator

from django.forms import ValidationError
from django.views.generic import TemplateView
from django.views.generic.base import View
from django.views.generic.edit import FormView, UpdateView, CreateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from . import forms


@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse('app:login'))

@login_required
def landing(request):
    return render(request, 'app/landing.html')


def login_view(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = forms.LoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect(reverse('app:landing'))
                else:
                    form.add_error(None, ValidationError(
                        "Your account is not active."
                    ))
            else:
                form.add_error(None, ValidationError(
                    "Invalid User Id of Password"
                ))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.LoginForm()

    return render(request, 'app/login.html', {'form': form})


def signup_view(request):
    if request.POST:
        form = forms.SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            try:
                user = get_user_model().objects.get(username=username)
                if user:
                    form.add_error(None, ValidationError("This user already exists."))
            except get_user_model().DoesNotExist:
                user = get_user_model().objects.create_user(username=username)

                # Set user fields provided
                user.set_password(password)
                user.first_name = first_name
                user.last_name = last_name
                user.email = email
                user.save()

                return redirect(reverse('app:login'))
    else:
        form = forms.SignupForm()

    return render(request, 'app/signup.html', {'form': form})


class UserProfile(UpdateView):
    form_class = forms.UserProfileForm
    template_name = "app/user_profile.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserProfile, self).dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return get_user_model().objects.get(pk=self.request.user.pk)

# testing Git. ignore this line.

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Friend Finder - Web Mapping 2017, Sample Application</title>

    {% load leaflet_tags %}
    {% load static %}

    {% leaflet_js plugins="forms" %}
    {% leaflet_css plugins="forms" %}

{#    <link rel="shortcut icon" href="{% static "Users/images/favicon.ico" %}" type="image/x-icon"/>#}
    <link rel="stylesheet" href="{% static "app/css/my_style.css" %}" type="text/css"/>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="{% static "app/js/my_script.js" %}"></script>
</head>
<body>

<header>
    <table style="width: 100%">
        <tr>
            <td class="app-header" style="text-align: left; width: 55%;">
                Friend Finder - Web Mapping 2017, Sample Application
            </td>
            <td class="app-header-small" style="text-align: right; width: 45%;">
                {% if user.is_authenticated %}
                    {{ user.get_full_name }} ({{ user.username }}) |
                    <a href="{% url 'app:userprofile' %}">My Profile</a> |
                    <a href="{% url 'app:logout' %}">Log Out</a>
                {% else %}
                    <a href="{% url 'app:login' %}">Log In</a> |
                    <a href="{% url 'app:signup' %}">Sign Up</a>
                {% endif %}
            </td>
        </tr>
    </table>
</header>


<div id="content">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/app/landing.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <p>General landing page. This is a <em>placeholder</em> pending development.</p>
{% endblock %}

templates/app/login.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <h3>Log In</h3>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p><span class="error">
                    <strong>{{ error|escape }}</strong>
                </span></p>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <p><span class="error">
                <strong>{{ error|escape }}</strong>
            </span></p>
        {% endfor %}
    {% endif %}


    {% if user.is_authenticated %}
        <p class="error">You are already logged in.</p>
    {% else %}

        <form method="post" action="{% url 'app:login' %}">
            {% csrf_token %}
            <table>
{#                <tr>#}
{#                    <td>{{ form.username.label_tag }}</td>#}
{#                    <td>{{ form.username }}</td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td>{{ form.password.label_tag }}</td>#}
{#                    <td>{{ form.password }}</td>#}
{#                </tr>#}
                {{ form.as_table }}
            </table>

            <input type="submit" value="Log In"/>
        </form>
    {% endif %}

{% endblock %}

templates/app/logout.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <p>Thank you for visiting. Come back soon.</p>
{% endblock %}

templates/app/signup.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <h3>Sign Up</h3>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p><span class="error">
                    <strong>{{ error|escape }}</strong>
                </span></p>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <p><span class="error">
                <strong>{{ error|escape }}</strong>
            </span></p>
        {% endfor %}
    {% endif %}

    {% if user.is_authenticated %}
        <p class="error">You are already logged in.</p>
    {% else %}

        <form method="post" action="{% url 'app:signup' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
                <tr>
                    <td>{{ form.password2.label_tag }}</td>
                    <td>{{ form.password2 }}</td>
                </tr>
                <tr>
                    <td>{{ form.first_name.label_tag }}</td>
                    <td>{{ form.first_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.last_name.label_tag }}</td>
                    <td>{{ form.last_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.email.label_tag }}</td>
                    <td>{{ form.email }}</td>
                </tr>
            </table>

            <input type="submit" value="Sign Up"/>
        </form>
    {% endif %}

{% endblock %}

templates/app/user_profile.html
{% extends "app/base.html" %}

{% load staticfiles %}
{% load leaflet_tags %}

{% block content %}
    <h3>User Profile</h3>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p><span class="error">
                    <strong>{{ error|escape }}</strong>
                </span></p>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <p><span class="error">
                <strong>{{ error|escape }}</strong>
            </span></p>
        {% endfor %}
    {% endif %}

    {% if user.is_authenticated %}
        <form method="post" action="{% url 'app:userprofile' %}">
            {% csrf_token %}
            <table style="padding: 10px; width: 100%">
                <tr>
                    <td style="text-align: right; font-family: sans-serif, Arial; font-style: italic; font-weight: normal">
                        Username
                    </td>
                    <td style="font-family: sans-serif, Arial; font-style: italic; font-weight: bold">{{ object.username }}</td>
                </tr>
                <tr>
                    <td style="text-align: right; font-family: sans-serif, Arial; font-style: italic; font-weight: normal">
                        Last login
                    </td>
                    <td style="font-family: sans-serif, Arial; font-style: italic; font-weight: bold">{{ object.last_login }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;">{{ form.first_name.label_tag }}</td>
                    <td>{{ form.first_name }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;">{{ form.last_name.label_tag }}</td>
                    <td>{{ form.last_name }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;">{{ form.email.label_tag }}</td>
                    <td>{{ form.email }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;"></td>
                    <td><input type="submit" value="Update Profile"/></td>
                </tr>
                {#                {{ form.as_table }}#}
            </table>


        </form>
    {% else %}
        <p class="error">You are not logged in.</p>
    {% endif %}

    <p id="geom" style="visibility: hidden; display: none">{{ object.last_location.geojson }}</p>

    <script>
        function map_init(map, options) {
            var geom = JSON.parse($("#geom").html());
            var myLatLon = L.latLng([geom.coordinates[1], geom.coordinates[0]]);

            geom = L.geoJson(geom);
            geom.addTo(map);

            map.setView(myLatLon, 16);
        }
    </script>

    <h3>Last known location</h3>
    <div style="text-align: center">
        {% leaflet_map "my_map" callback="map_init" %}
    </div>

{% endblock %}